services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3337:3336
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/Group3
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:3623/wd/hub
    ports:
      - "3333:3333"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 3623:3623
volumes:
  mysql_data:
  bundle_data:
  node_modules:
